version: '3.4'

services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "abcDEFG123!"
    ports:
      - "127.0.0.1:1433:1433"


  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
        - "8080:8080"
        - "4300:4300"
